// Action Types
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';

export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';

export const TOGGLE_CARD_FREEZE_REQUEST = 'TOGGLE_CARD_FREEZE_REQUEST';
export const TOGGLE_CARD_FREEZE_SUCCESS = 'TOGGLE_CARD_FREEZE_SUCCESS';
export const TOGGLE_CARD_FREEZE_FAILURE = 'TOGGLE_CARD_FREEZE_FAILURE';
